SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')), COUNT(ANIMAL_ID) 
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME, 'HH24') >= '09' AND TO_CHAR(DATETIME, 'HH24') <= 19
GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
ORDER BY 1